config/routes.rb
Movieproject::Application.routes.draw do
  
  post "/login" => "pages#login", as: :login
  get "/logout" => "pages#logout", as: :logout
  
  delete "/remove/:id" => "pages#destroy", as: :delete_movie
  
  get "/add/:imdb_id" => "pages#add_movie", as: :add_movie
  
  get "/rate/:id/:like" => "pages#rate", as: :rate
  
  root to: "pages#index"
  

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :ratings, dependent: :destroy
  
  def good
    ratings.good.count > 99 ? "99+" : ratings.good.count
  end
  
  def bad
    ratings.bad.count > 99 ? "99+" : ratings.bad.count
  end
  
  def self.without_user(user)
    if Rating.where("user_id = ?", user.id).count == 0
      self
    else
      where("id not in (?)", (Rating.where("user_id = ?", user.id).map(&:movie_id)))
    end
  end
  
  def self.scrape_imdb(imdb_id)
    return nil if find_by_imdb(imdb_id)
    
    require 'open-uri'
    new_movie = Movie.new(imdb: imdb_id)
    doc = Nokogiri::HTML(open("http://www.imdb.com/title/#{imdb_id}/"))
    title = /^(.+) \((\d{4})\)$/.match(doc.css("title").inner_text.gsub(/IMDb - /i, "").gsub(/ - imdb/i, "")) # gets title
    
    new_movie.title = title[1]
    new_movie.year = title[2].to_i
    new_movie.runtime = /(\d+) min.+$/.match(doc.css(".infobar").inner_text)[1].to_i
    new_movie.description = doc.css("p[itemprop=description]").inner_text.gsub("\n", " ")
    new_movie.imdb = imdb_id
    new_movie.youtube = get_youtube(new_movie.title)
    new_movie.save
    
  end
  
  def self.get_youtube(title)
    require 'open-uri'
    doc = Nokogiri::HTML(open("http://www.youtube.com/results?search_query=#{title.gsub(" ", "+")}+trailer&search_duration=short"))
    doc.css("#search-results h3 a").first['href'].gsub("/watch?v=", "")
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
  
  validates :user, presence: true
  validates :movie, presence: true
  
  scope :good, where("ratings.like IS true")
  scope :bad, where("ratings.like IS false")
  
  scope :latest, where("ratings.like IS NOT ?", nil).order("created_at DESC").limit(10).includes(:user, :movie)
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  has_many :ratings, dependent: :destroy
  attr_accessible :username, :password
  
  validates :username, presence: true,
                       format: {with: /^\w+$/},
                       uniqueness: {case_sensitive: false}
                       
  validates :password, presence: {on: :create}
  
  validates :password_confirmation, presence: {on: :create}
  
  scope :with_username, lambda { |username| where("UPPER(username) = ?", username.upcase) }
  
  def hide_movie(movie, like = nil)
    ratings.create(movie: movie, like: like) unless ratings.find_by_movie_id(movie.id)
  end
  
  def self.username_taken?(username)
    with_username(username).count > 0
  end
  
  def self.authenticate(username, password)
    User.where("UPPER(username) = ?", username.upcase).try(:first).try(:authenticate, password)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery
  
  helper_method :current_user, :logged_in?, :admin?
  
  private
    def current_user
      @current_user ||= User.find_by_id(cookies.signed[:user_id])
    end
    
    def logged_in?
      !!current_user
    end
    
    def admin?
      logged_in? && current_user.admin?
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :check_login, only: [:rate]
  before_filter :check_admin, only: [:destroy, :add_movie]
  
  def index
    if logged_in?
      if Movie.without_user(current_user).count == 0
        @movie = nil
      else
        @movie = Movie.without_user(current_user).offset(rand(Movie.without_user(current_user).count)).limit(1).first
      end
    else
      @movie = Movie.offset(rand(Movie.count)).limit(1).first
    end
    @feed = Rating.latest
    render "no_movies" unless @movie
  end
  
  def destroy
    Movie.find(params[:id]).destroy
    redirect_to root_path, notice: "Movie deleted."
  end
  
  def login
    user = User.authenticate(params[:login][:username], params[:login][:password])
    if user
      session[:login] = nil
      cookies.permanent.signed[:user_id] = user.id
      redirect_to root_path, notice: "Welcome back."
    elsif User.username_taken?(params[:login][:username])
      session[:login] = nil
      redirect_to root_path, alert: "Wrong password."
    else
      user = User.new(params[:login])
      user.password_confirmation = session[:login][:password] if session[:login] && params[:login][:username] == session[:login][:username]
      if user.save
        session[:login] = nil
        cookies.permanent.signed[:user_id] = user.id
        redirect_to root_path, notice: "Registered and logged in."
      elsif user.errors.messages[:username]
        session[:login] = nil
        redirect_to root_path, alert: "Bogus username! Only use letters, numbers and underscore."
      else
        session[:login] = params[:login]
        redirect_to root_path, notice: "Type in the password again to register."
      end
    end
  end
  
  def rate
    if movie = Movie.find_by_id(params[:id])
      current_user.hide_movie(movie, check_rating(params[:like]))
      redirect_to root_path
    else
      redirect_to root_path, alert: "Could not find the movie."
    end
  end
  
  def logout
    cookies.permanent.signed[:user_id] = nil
    redirect_to root_path, notice: "You have logged out."
  end
  
  def add_movie
    redirect_to(root_path, alert: "The was already in the database.") and return unless Movie.scrape_imdb(params[:imdb_id])
    @movie = Movie.find_by_imdb(params[:imdb_id])
    @feed = Rating.latest
    render "index"
  end
  
  private
  
    def check_login
      redirect_to root_path, alert: "You need to login to rate." unless logged_in?
    end
    
    def check_admin
      redirect_to root_path, alert: "You have to be admin to do that." unless admin?
    end
    
    def check_rating(rating)
      if rating == "yes"
        true
      elsif rating == "no"
        false
      else
        nil
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def feed_item_class(like)
    like ? "feed-pro" : "feed-con"
  end
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title Flicktipster
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    link href='http://fonts.googleapis.com/css?family=Merienda+One' rel='stylesheet' type='text/css'
    = csrf_meta_tags
  body
    - unless logged_in?
      #top-bar
      		.top-bar-inner
      			form action="#{login_path}" method="post"
      				input.login-form.username-form name="login[username]" type="text" placeholder="Username" value="#{session[:login][:username] if session[:login]}"
      				input.login-form.password-form name="login[password]" type="password" placeholder="Password"
      				input.login-form-button.button.blue name="login-button" type="submit" value="Login" 
    #container
    		.logo
    			h1 
    			  | Flicktipster
    			  span style="font-size: 0.8em;".com
    		.login-link-container
    			- unless logged_in?
    			  a.login-link 
    				span.login Log in
    				span.info  [?]
    			- else
    			  p.logged-in 
    			    ' Logged in as #{current_user.username}, #{link_to "log out", logout_path}.
    		#flash
    		  - if flash.alert
    		    .alert
    		      p = flash[:alert]
    		  - if flash.notice
    		    .notice
    		      p = flash[:notice]
    		= yield
  		
    #overlay-bg

    #overlay
    		#overlay-inner
    			p To register, just log in with a desired username and password – and a user
    			   will automatically be created for you

    == render partial: "analytics"

app/views/pages/_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-24348175-2']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/pages/_feed_item.html.slim
.feed-item
	p data-youtube="#{feed_item.movie.youtube}" data-title="#{feed_item.movie.title}" data-runtime="#{feed_item.movie.runtime}" data-description="#{feed_item.movie.description}"
		span class="#{feed_item_class(feed_item.like)}"
		= feed_item.movie.title
		small
			span.username
				=' feed_item.user.username
			=' time_ago_in_words(feed_item.created_at, true) + " ago"

app/views/pages/index.html.slim
.youtube
  iframe width="560" height="315" src="http://www.youtube.com/embed/#{@movie.youtube}?rel=0&amp;hd=1&amp;wmode=Opaque&amp;showinfo=0&amp;iv_load_policy=3" frameborder="0" allowfullscreen>
	
.movie-info
	.con
		= "#{@movie.bad}"
	.pro
		= "#{@movie.good}"
	h2 = "#{@movie.title} (#{@movie.year})"
	p = @movie.runtime.to_s + " minutes"
	p = @movie.description


.fetch
  = link_to "Fetch a new movie", root_path, class: "fetch-movie button orange"

- if logged_in?
	.express
		a.show.button.white href="#show" Rate and hide movie
		.choices
		  a.vote-up.button.green href="/rate/#{@movie.id}/yes" I&#x27;ve seen it – and liked it
		  br
			a.vote-down.button.red href="/rate/#{@movie.id}/no" I&#x27;ve seen it – and didn&#x27;t like it 
			br
			a.vote-nothing.button.gray href="/rate/#{@movie.id}/hide" I haven&#x27;t seen it but don&#x27;t show this movie again 
		- if admin?
		  = link_to "Delete movie", delete_movie_path(@movie), method: :delete, :class => [:delete, :button, :red]
		  br
		  a.bookmarklet href="javascript: var url = document.location.href; var href = 'http://flicktipster.com/'; var urlArray = url.split('/'); var imdbCode = urlArray[4]; window.open(href+'add/'+imdbCode,'flicktipster','toolbar=0,resizable=1,scrollbars=0,status=1,width=490,height=400');"
		  	' Add to Flicktipster
		  br
		  	
.feed 
	= render partial: "feed_item", collection: @feed, as: :feed_item

app/views/pages/no_movies.html.slim
p.sad-face :-(
p 
  ' Man! We are all out of movies and you watch waaaay too many. Might we recommend you to 
  a href="http://lmgtfy.com/?q=how+to+read+books+for+dummies" read a book
  = " "
  ' instead? Or perhaps it&apos;s time for you to get some excersise?

.fetch

.feed 
	= render partial: "feed_item", collection: @feed, as: :feed_item